### ISSUE TITLE
How to animate the gauge?

### ISSUE THREAD

**Issue by elochai90** [1995parham/react-canvas-gauges#1]
Hi,

how can I animate the gauge? Tried it with the radial gauge sample but there's no animation

```
import React from 'react';
import { RadialGauge } from 'react-canvas-gauges';

[...]

class Gauge extends React.Component {
  componentDidMount() {
    var gauge = new RadialGauge({
        renderTo: 'canvas-id'
      }).draw();
    }

  [...]

  render() {
    /** nothing animated here... */
    return <canvas id="canvas-id" datatype="radial-gauge"/>;
  }
}
```

Thanks!

**Comment by 1995parham** [comment]
By animate you mean change the value of gauge and it renders to the new value? I doing this [here](https://github.com/Nahalco/CEIT-UI/blob/master/src/components/widgets/Multisensor.jsx)

**Comment by elochai90** [comment]
So your're just setting the gauge's value by an reactive value? That did't work for me :( I suppose the gauge without settings (as in my commented above) is meant to be animated? Then I'd have to search for the issue outside my component.

**Comment by 1995parham** [comment]
Yes, I just set that by a reactive value. I think it's better to remove the `draw` part from your code and use following code in your HTML part:

```jsx
 <canvas ref={(canvas) => {
    this.el = canvas
 }} />
```

I think [this](https://github.com/1995parham/react-canvas-gauges/blob/master/src/RadialGauge.jsx) may help.

**Comment by maxsd** [comment]
Hey, this issue is closed but while trying a sample i can't see any animation when changing the value. I change values with a simple setInterval(). Value is updated, needle moves to the correct value but without any animation. I tried adding animationDuration and animationRule to the component and it's still the same.

`        <RadialGauge
          value={this.state.angleValue}
          animationDuration={1500}
          animationRule={'linear'}
        />`

Any clue ?

**Comment by scraimer** [comment]
@maxsd I've discovered (quite by accident) that the gauges fail to show the animation only when `react-canvas-gauges` is installed using `npm` into `node_modules`.

You can get he animation to work if you copy the `react-canvas-gauges` directly into your source tree.  I'm going to write the instructions to do this here, in case I ever need to do it again:

    $ cd your-project/src
    $ git submodule add https://github.com/1995parham/react-canvas-gauges.git

Then change the import line to import from that directory. For example, if you used `import {RadialGauge} from 'react-canvas-gauges'`, replace it with `import {RadialGauge} from './react-canvas-gauges'`

This is not a solution, just a workaround.
